global:
    scrape_interval: 30s
    evaluation_interval: 30s

scrape_configs:
    - job_name: stremio-double-subtitles
      metrics_path: /metrics
      scheme: https
      bearer_token: ${{ secrets.METRICS_TOKEN }}
      static_configs:
          - targets:
                - stremio-double-subtitles
